### PR TITLE
Transfer Learning - Finalized Draft - Jake Dalli

### PR DESCRIPTION
**Pull request by jkdll**
Hi,
I've updated a finalized version of the document - if you do not have any feedback (or if it's to late for feedback) please consider it to be the final submission unless I submit another pull request.

Thanks,
Jake

### CODE REVIEW

**Comment by jkdll** [comment]
@jp-um - the project spec said that the word limit is 1000 words and 4 pages max. I kept to the word limit, however if I am allowed I can add more.

**Comment by jkdll** [comment]
@jp-um  I have updated the document as per your feedback:
- The entry is a bit dry (3 pages, but your limit is 4 I think) -- can you expand a bit.- _kindly advise if I should skip the world limit, and which part you think I should expand if possible..._
- You have to say in the figure caption if the figure was lifted from another paper/source (e.g. Reproduced from Ebejer et al (2017)) _I added references to two figures and the images, all images permit commercial re-use._
- Can you fix this? Warning--empty title in torrey2009 (bib) _fixed._
- Do not manually call newpage (point 31 in the guidelines) ... ghax imbaghad nigi biex inbiddel il font size jew il margins u tkissirli kollox. _I removed the newpage calls._

**Comment by jp-um** [comment]
You can use the 4pg limit if you want to add something more.  Advise me what you are going to do, so I'll know whether to merge or not.

**Comment by jp-um** [comment]
Merged.

**Pull request merged**
