### PR TITLE
Dimensionality Reduction Glossary Entry

### PR DESCRIPTION
**Pull request by stefancassar**
Pull request for draft commit.

### CODE REVIEW

**Comment by jp-um** [comment]
Also when you take an image from somewhere you need to say something like "Reproduced from Ebejer et al. (2017)."  In the caption

**Comment by stefancassar** [comment]
Please find commit with requested changes.

Thanks

**Comment by jp-um** [comment]
I had to fix missing entries (year) in your bib file...

Merged.

**Comment by jp-um** [comment]
"PrincipLE Component [..]" stajna ingibuh tajjeb il heading.

**Pull request merged**
