### PR TITLE
Empirical Risk Minimisation - Neil Farrugia

### PR DESCRIPTION
**Pull request by neilf95**
Fixed issues. Compiled using pdflatex and generated pdf.

### CODE REVIEW

**Comment by jp-um** [comment]
I made some notes on the other PR, you need to fix.  Please do not reopen a new PR keep on the (other) thread.  Merge these changes there.

**Comment by neilf95** [comment]
Applied the suggested changes.

Was unable to commit to other pull request as I had to delete the branch and re-create it due to complications.

**Comment by jp-um** [comment]
Once again this entry is broken.  You bib file is called `empiricalriskminmisation_nf.bib` while you reference `empiricalriskminimisation_nf` in the tex file (spelling and careless mistake).  Fix and make sure you do not submit a broken entry again.

**Comment by neilf95** [comment]
Apologies for the mistakes.

Ensured that the pdf generated well, no bibtex or latex errors.

**Comment by jp-um** [comment]
**See Guideline 29.**  You still have a ton of warnings in your .bib file.  Please fix, and make sure you get it right this time.

> Warning--empty institution in Vapnik
> Warning--empty year in Vapnik
> Warning--empty year in Vapnik
> Warning--empty publisher in principles
> Warning--empty institution in Wehenkel2018

**Comment by jp-um** [comment]
Merged, thanks.

**Pull request merged**
