### PR TITLE
Classification Chapter - Claire

### PR DESCRIPTION
**Pull request by ClaireGalea**
Initial commit for Classification Glossary Chapter

### CODE REVIEW

**Comment by ClaireGalea** [comment]
Thank you for your feedback. In relation to your first comment, is it correct to say that clustering is an unsupervised classification method?

With regards to the algorithms included in my uploaded glossary, would it still make sense to keep 2 of them as examples of supervised classification algorithms ?

I will add a section which compares classification to regression, and expand more on multiclass classification.

**Comment by jp-um** [comment]
Dear Claire,

Supervised/Unsupervised and Classification/Regression are orthogonal to each other (you can have an unsupervised regression method also).  The peter flasch book has something about this at the beginning (IIRC).  

I dont think you should focus on algorithms per se ... leave that to the people who are doing those in detail.

**Comment by ClaireGalea** [comment]
Fixed my entry according to your feedback. Changes are committed, thanks :)

**Comment by jp-um** [comment]
Still not there.

Don't start your entry with Data Mining, that is something very specific.  This is a Machine Learning handbook so ...

Also you have the following bib problems ... please fix

> Warning--empty publisher in james2006
> Warning--empty publisher in jiawei2011
> Warning--empty institution in kumar2002
> Warning--empty publisher in rokach2007
> Warning--empty institution in sagar2017

**Comment by jp-um** [comment]
I fixed some minor stuff for you.  Regression should be as a separate index entry (independent of classification).  Also use italics for specific reason, not for words which catch your fancy.  Anyway...

Merged, Thanks!

**Pull request merged**
